/* Copyright 2026 Google LLC. Licensed under the Apache License, Version 2.0. */
package com.google.ai.edge.gallery.customtasks.flux.transformer

import android.content.res.AssetManager
import java.io.InputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.MessageDigest
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

class FluxPhase2gEvidenceException(message: String, cause: Throwable? = null) :
  IllegalArgumentException(message, cause)

/** Validated immutable Phase 2G host inputs. Array access is always defensively owned. */
class FluxPhase2gEvidence internal constructor(
  private val initial: FloatArray,
  private val timestepRows: FloatArray,
  private val sigmaDeltas: FloatArray,
  private val rotaryCos: FloatArray,
  private val rotarySin: FloatArray,
) {
  fun initialLatents() = initial.copyOf()
  fun timestep(step: Int) = timestepRows.copyOfRange(step * 3_072, (step + 1) * 3_072)
  fun dsigma(step: Int) = sigmaDeltas[step]
  fun cos() = rotaryCos.copyOf()
  fun sin() = rotarySin.copyOf()
}

/** Strict, platform-neutral parser for the supplied authoritative evidence. */
object FluxPhase2gEvidenceParser {
  const val DIRECTORY = "flux/phase2g"
  const val BASE_REVISION = "e7b7dc27f91deacad38e78976d1f2b499d76a294"
  const val COMPANION_REVISION = "f48a89e4f29a74ab51f29c311ac7a0e5e479d225"
  const val GENERATOR_SHA = "1f2b3d902d4f36281e61447d86331e08bd1c61f20f9034896817c086ae1ab61d"
  private val json = Json { ignoreUnknownKeys = false }
  private val contracts = linkedMapOf(
    "latents0.bin" to Contract(listOf(1, 256, 128), 32_768, 131_072, "81c0e15a45448c9d8e8e449d02146c33fb7561aee039b0755cd5168e4ee2956b"),
    "temb.bin" to Contract(listOf(4, 3072), 12_288, 49_152, "c61e8934b1474620c4fe5b1cd387005f4673dae939b5e5432bb38fd8c3bc1cce"),
    "dsigma.bin" to Contract(listOf(4), 4, 16, "f69390537e24ea71a5b3c46954fc923aae52d40e049fa054e289134aa0ea7cfa"),
    "cos.bin" to Contract(listOf(1, 1024, 1, 64), 65_536, 262_144, "d45b2bb837a8e543ceae238e8dc72cbfcdbec7268fa691b722994a1f08ab68cc"),
    "sin.bin" to Contract(listOf(1, 1024, 1, 64), 65_536, 262_144, "657c868835d8622d791eef27dead19b2dad910014e6bd39343e6721efc0b13a3"),
  )

  fun parse(open: (String) -> InputStream): FluxPhase2gEvidence = try {
    val metadata = open("flux_phase2g_constants.json").use { json.decodeFromString<Metadata>(it.readBytes().decodeToString()) }
    validateMetadata(metadata)
    val values = contracts.mapValues { (name, contract) ->
      val bytes = open(name).use { it.readBytes() }
      if (bytes.size != contract.bytes) fail("$name has an invalid byte count.")
      val digest = MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }
      if (digest != contract.sha) fail("$name failed SHA-256 validation.")
      ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).let { buffer -> FloatArray(contract.count) { buffer.float } }
        .also { if (it.any { value -> !value.isFinite() }) fail("$name contains a non-finite value.") }
    }
    if (values.getValue("dsigma.bin").any { it >= 0f }) fail("dsigma.bin values must be negative.")
    FluxPhase2gEvidence(values.getValue("latents0.bin"), values.getValue("temb.bin"), values.getValue("dsigma.bin"), values.getValue("cos.bin"), values.getValue("sin.bin"))
  } catch (known: FluxPhase2gEvidenceException) { throw known }
    catch (failure: Exception) { throw FluxPhase2gEvidenceException("FLUX Phase 2G evidence validation failed.", failure) }

  private fun validateMetadata(m: Metadata) {
    if (m.schemaVersion != 1 || m.mode != "image-editing" || m.seed != 1234 || m.steps != 4 ||
      m.baseModelRepository != "black-forest-labs/FLUX.2-klein-4B" || m.companionRepository != "google-ai-edge/litert-samples" ||
      m.immutableBaseModelRevision != BASE_REVISION || m.immutableCompanionRevision != COMPANION_REVISION ||
      m.originalGeneratorScriptSha256 != GENERATOR_SHA || m.generatorScriptPath != "compiled_model_api/text_to_image/flux2_klein_kotlin_gpu/conversion/gen_prep_klein.py" ||
      m.authenticationPatchedScriptSha256 != "4f9dbc4c48998da80489978752e275a99b453f4cce5a0e29174431c490fb7a94" ||
      m.generatedAt != "2026-07-30T06:16:43.736255+00:00" || m.pythonVersion != "3.12.13" || m.pytorchVersion != "2.9.0+cpu" ||
      m.extractionLibraries != Libraries("1.14.0", "0.39.0", "1.25.1", "2.0.2", "0.8.0", "5.14.1") ||
      m.provenanceStatement != "The five files were generated by the recorded pinned companion algorithm from the recorded immutable base-model revision. The local script modification supplied only HF_TOKEN and the immutable revision to from_pretrained." ||
      m.purpose != "FLUX Phase 2G editing host inputs" || m.imageSize != listOf(256, 256) || m.artifacts.keys != contracts.keys) fail("Metadata provenance does not match Phase 2G.")
    contracts.forEach { (name, c) ->
      val a = m.artifacts[name]
      if (a == null || a.shape != c.shape || a.elementCount != c.count || a.byteCount != c.bytes || a.sha256 != c.sha ||
        a.dtype != "float32" || a.numpyDtype != "<f4" || a.byteOrder != "little-endian") fail("$name metadata contract is invalid.")
    }
  }
  private fun fail(message: String): Nothing = throw FluxPhase2gEvidenceException(message)
  private data class Contract(val shape: List<Int>, val count: Int, val bytes: Int, val sha: String)
  @Serializable private data class Artifact(val byteCount: Int, val byteOrder: String, val dtype: String, val elementCount: Int, val numpyDtype: String, val sha256: String, val shape: List<Int>)
  @Serializable private data class Libraries(val accelerate: String, val diffusers: String, val huggingface_hub: String, val numpy: String, val safetensors: String, val transformers: String)
  @Serializable private data class Metadata(
    val artifacts: Map<String, Artifact>, val authenticationPatchedScriptSha256: String,
    val baseModelRepository: String, val companionRepository: String, val extractionLibraries: Libraries,
    val generatedAt: String, val generatorScriptPath: String, val imageSize: List<Int>,
    val immutableBaseModelRevision: String, val immutableCompanionRevision: String, val mode: String,
    val originalGeneratorScriptSha256: String, val provenanceStatement: String, val purpose: String,
    val pythonVersion: String, val pytorchVersion: String, val schemaVersion: Int, val seed: Int, val steps: Int,
  )
}

class FluxPhase2gEvidenceLoader(private val assets: AssetManager) {
  @Volatile private var cached: FluxPhase2gEvidence? = null
  fun load(): FluxPhase2gEvidence = cached ?: synchronized(this) {
    cached ?: FluxPhase2gEvidenceParser.parse { assets.open("${FluxPhase2gEvidenceParser.DIRECTORY}/$it") }.also { cached = it }
  }
}
